name: Deploy Next.js site

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: Asia/Taipei

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: "lts/*"
        cache: "npm"

    - name: Restore cache
      uses: actions/cache@v4
      with:
        path: |
          .next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

    - name: Install dependencies
      run: npm ci

    - name: Build with Next.js
      run: npm run build

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    - name: SSH and rebuild
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: yuyu1015
        password: ${{ secrets.PASSWORD }}
        script: |
          cd /home/yuyu1015/weather-dashboard
          git pull
          docker compose up -d --build weather-dashboard
