name: Deploy Next.js site

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: Asia/Taipei

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Restore cache
      uses: actions/cache@v4
      with:
        path: |
          .next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lockb') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lockb') }}-

    - name: Install dependencies
      run: bun i

    - name: Build with Next.js
      run: bun run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: SSH and rebuild
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: yuyu1015
        password: ${{ secrets.PASSWORD }}
        script: |
          cd /home/yuyu1015/weather-dashboard
          git pull
          docker compose up -d --build weather-dashboard
